project_id = "lvnnripwnkjpgklgypnv"

[functions.analyze-exceptions]
verify_jwt = false

[functions.analyze-seasonality]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.log-login]
verify_jwt = false

[functions.log-question]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.generate-learnings]
verify_jwt = false

[functions.sensiwatch-data]
verify_jwt = false

[functions.sensiwatch-push]
verify_jwt = false
